name:                align
version:             0.1.0.0
github:              "githubuser/align"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/align#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- mtl
- transformers
- containers
- safe
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Werror

default-extensions:
- ConstraintKinds
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DataKinds
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

executables:
  align:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - align
    - optparse-generic

tests:
  align-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - align
    - hspec
